pcm.!default {
    type asym
    playback.pcm "dmixer"
    capture.pcm "hw:sndrpihifiberry,0"
}

pcm.dmixer {
    type dmix
    ipc_key 1024
    slave {
        pcm "hw:sndrpihifiberry,0"
        rate 44100
        format S16_LE
    }
}

ctl.!default {
    type hw
    card sndrpihifiberry
}
